language: node_js

sudo: false

cache:
  directories:
    - node_modules

node_js:
  - 10.16.3

install: yarn install
script: yarn test

notifications:
  email:
    on_success: never
    on_failure: change
